---
name: logservice

instance_groups:
  - name: logservice
    azs: [z1,z2,z3]
    instances: 3
    jobs:
      - name: bpm
        release: bpm
      - name: logservice
        release: logservice
        properties:
          logservice:
            syslog_addresses:
              - id: cada65a0-c972-4ccf-8eb2-bc58b0d147cb
                name: loghost
                company_id: apps@1368
                description: Drain apps logs to loghost
                default_drain_type: "" # can be logs (similar to empty), metrics or all
                bullets:
                  - "Available create parameters:"
                  - "- s"
                  - "- env"
                  - "- audience"
                urls:
                  - tcp://loghost.example.net:1512
                tags:
                  s: "{{.Space}}"
                  env: "{{if hasSuffix .Org \"-staging\" }}dev{{ else }}prod{{ end }}"
                  audience: "mycompagny"
                  fmt: "json"
            web:
              tls:
                cert: ((log_service_ssl.certificate))
                key: ((log_service_ssl.private_key))
            broker:
              public_host: logservice.((system_domain))
              drain_host: logservice.service.cf.internal
              username: logservice-broker
              password: ((logservice-broker-password))
            db:
              user: logservice
              password: ((logservice-mysql-password))
              host: database.service.cf.internal
              database: logservice
            forwarder:
              allowed_hosts:
                - logservice.service.cf.internal

      - name: route_registrar
        release: routing
        consumes:
          nats:
            from: nats
            deployment: cf
        properties:
          route_registrar:
            routes:
              - name: logservice
                registration_interval: 20s
                server_cert_domain_san: "logservice.service.cf.internal"
                tls_port: 8089
                uris:
                  - logservice.((system_domain))
    vm_type: default
    stemcell: default
    networks:
      - name: default

variables:
  - name: logservice-broker-password
    type: password
  - name: log_service_ssl
    options:
      ca: /((director_name))/cf/service_cf_internal_ca
      alternative_names:
        # backward compatibility, to remove on next release
        - logservice.service.cf.internal
        - logservice.service.logservice.internal
      common_name: logserviceSSL
    type: certificate

update:
  canaries: 1
  max_in_flight: 32
  canary_watch_time: 1000-100000
  update_watch_time: 1000-100000
  serial: false

stemcells:
  - alias: default
    os: ubuntu-xenial
    version: latest

manifest_version: v2.0.0

releases:
  - name: logservice
    version: 2.2.0
    url: https://github.com/orange-cloudfoundry/logservice-release/releases/download/v2.0.0/logservice-2.0.0.tgz
  - name: bpm
    version: latest
  - name: routing
    version: latest
