---
name: logservice

instance_groups:
  - name: logservice
    azs: [z1,z2,z3]
    instances: 3
    jobs:
      - name: bpm
        release: bpm
      - name: broker-registrar
        release: logservice
        properties:
          cf:
            api_url: https://api.((system_domain))
            username: admin
            password: ((/((director_name))/cf/cf_admin_password))
            skip_ssl_validation: true
          logservice:
            broker:
              host: logservice.service.logservice.internal
              protocol: https
              port: 8089
              name: logs
              username: logservice-broker
              password: ((logservice-broker-password))
              public_plans: [loghost]
      - name: logservice
        release: logservice
        properties:
          logservice:
            syslog_addresses:
              - id: cada65a0-c972-4ccf-8eb2-bc58b0d147cb
                name: loghost
                company_id: apps@1368
                description: Drain apps logs to loghost
                default_drain_type: "" # can be logs (similar to empty), metrics or all
                bullets:
                  - "Available create parameters:"
                  - "- s"
                  - "- env"
                  - "- audience"
                urls:
                  - tcp://loghost.example.net:1512
                tags:
                  s: "{{.Space}}"
                  env: "{{if hasSuffix .Org \"-staging\" }}dev{{ else }}prod{{ end }}"
                  audience: "mycompagny"
                  fmt: "json"
            ssl_cert: ((log_service_ssl.certificate))
            ssl_key: ((log_service_ssl.private_key))
            broker:
              username: logservice-broker
              password: ((logservice-broker-password))
            syslog_drain_url: https://logservice.service.logservice.internal:8089
            skip_ssl_validation: false
            mysql:
              user: logservice
              password: ((logservice-mysql-password))
              host: database.service.cf.internal
              database: logservice
            external_url: https://logservice.((system_domain))
            disallow_logs_from_external: true
      - name: route_registrar
        release: routing
        consumes:
          nats:
            from: nats
            deployment: cf
        properties:
          route_registrar:
            routes:
              - name: logservice
                registration_interval: 20s
                server_cert_domain_san: "logservice.service.logservice.internal"
                tls_port: 8089
                uris:
                  - logservice.((system_domain))
    vm_type: default
    stemcell: default
    networks:
      - name: default

variables:
  - name: logservice-broker-password
    type: password
  - name: log_service_ssl
    options:
      ca: /((director_name))/cf/service_cf_internal_ca
      alternative_names:
        # backward compatibility, to remove on next release
        - logservice.service.cf.internal
        - logservice.service.logservice.internal
      common_name: logserviceSSL
    type: certificate

update:
  canaries: 1
  max_in_flight: 32
  canary_watch_time: 1000-100000
  update_watch_time: 1000-100000
  serial: false

stemcells:
  - alias: default
    os: ubuntu-xenial
    version: latest

manifest_version: v1.5

releases:
  - name: logservice
    version: "1.11"
    url: https://github.com/orange-cloudfoundry/logservice-release/releases/download/v1.11/logservice-1.11.tgz
    sha1: 611d5f107411ddd2ed37ee5b8a5a8b9cd6102b2c
  - name: bpm
    version: latest
  - name: routing
    version: latest
