{
 "title": "Overview",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(logs_sent_total, instance)"
   }
  ]
 },
 "panels": [
  { "title": "Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Bosh jobs",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "min(bosh_job_healthy{bosh_job_name=\"logservice\"})"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(rate(logs_sent_errors_total[10m])) OR on() vector(0)"
    }
   ]
  },
  { "title": "Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Success Rate (log/s in success)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(logs_sent_total{instance=~\"$instance\"}[10m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Error Rate (log/s in error)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(logs_sent_errors_total{instance=~\"$instance\"}[10m])) by (instance) or on() vector(0)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Q.O.S.",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(sum(logs_sent_duration_bucket{le=\"0.005\", instance=~\".*\"}) by (instance,le)  / on(instance) group_left sum(logs_sent_duration_count{instance=~\"$instance\"}) by (instance,le)) * 100",
     "legendFormat": "5 ms / {{instance}}"
    },
    {
     "expr": "(sum(logs_sent_duration_bucket{le=\"0.010\", instance=~\"$instance\"}) by (instance,le)  / on(instance) group_left sum(logs_sent_duration_count{instance=~\"$instance\"}) by (instance,le)) * 100",
     "legendFormat": "10 ms / {{instance}}"
    },
    {
     "expr": "(sum(logs_sent_duration_bucket{le=\"0.1\", instance=~\"$instance\"}) by (instance,le)  / on(instance) group_left sum(logs_sent_duration_count{instance=~\"$instance\"}) by (instance,le)) * 100",
     "legendFormat": "100 ms / {{instance}}"
    },
    {
     "expr": "(sum(logs_sent_duration_bucket{le=\"0.25\", instance=~\"$instance\"}) by (instance,le)  / on(instance) group_left sum(logs_sent_duration_count{instance=~\"$instance\"}) by (instance,le)) * 100",
     "legendFormat": "250 ms / {{instance}}"
    },
    {
     "expr": "(sum(logs_sent_duration_bucket{le=\"0.5\", instance=~\"$instance\"}) by (instance,le)  / on(instance) group_left sum(logs_sent_duration_count{instance=~\"$instance\"}) by (instance,le)) * 100",
     "legendFormat": "500ms  / {{instance}}"
    },
    {
     "expr": "(sum(logs_sent_duration_bucket{le=\"1\", instance=~\"$instance\"}) by (instance,le)  / on(instance) group_left sum(logs_sent_duration_count{instance=~\"$instance\"}) by (instance,le)) * 100",
     "legendFormat": "1000 ms  / {{instance}}"
    }
   ]
  },
  {
   "title": "Reponse times",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum(rate(logs_sent_duration_bucket[10m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  { "title": "Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Log per Space",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 34 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(logs_sent_total{}[$__range])) by (org, space)",
     "legendFormat": "{{org}} / {{space}}"
    }
   ]
  },
  {
   "title": "Log per Org",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 34 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(logs_sent_total{}[$__range])) by (org)",
     "legendFormat": "{{org}}"
    }
   ]
  },
  {
   "title": "Log per Instance",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 34 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(logs_sent_total{}[$__range])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Log per Plan",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 43 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(logs_sent_total{}[$__range])) by (plan_name)",
     "legendFormat": "{{plan_name}}"
    }
   ]
  },
  {
   "title": "Log per App",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 16, "x": 8, "y": 43 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(logs_sent_total{}[$__range])) by (app, org, app)",
     "legendFormat": "{{org}} / {{space}} / {{app}}"
    }
   ]
  }
 ]
}