releases:
  - name: logservice
    version: "1.10"
    url: https://github.com/orange-cloudfoundry/logservice-release/releases/download/v1.10/logservice-1.10.tgz
    sha1: 4054766394aea737cb253c6923a23a3084c6e520

addons:
  - name: logsearch-dns
    exclude:
      deployments: ["logservice", "logsearch"]
    jobs:
      - name: logsearch-dns
        release: logservice
