releases:
  - name: logservice
    version: "1.6"
    url: https://github.com/orange-cloudfoundry/logservice-release/releases/download/v1.6/logservice-1.6.tgz
    sha1: 4eda1580401732eac4f76b179b9b298c0973f395

addons:
  - name: logsearch-dns
    exclude:
      deployments: ["logservice", "logsearch"]
    jobs:
      - name: logsearch-dns
        release: logservice
