releases:
  - name: logservice
    version: "1.8"
    url: https://github.com/orange-cloudfoundry/logservice-release/releases/download/v1.8/logservice-1.8.tgz
    sha1: 084ec5e0767551be2bb1e68f0587aafa32632dd0

addons:
  - name: logsearch-dns
    exclude:
      deployments: ["logservice", "logsearch"]
    jobs:
      - name: logsearch-dns
        release: logservice
