releases:
  - name: logservice
    version: "1.11"
    url: https://github.com/orange-cloudfoundry/logservice-release/releases/download/v1.11/logservice-1.11.tgz
    sha1: 611d5f107411ddd2ed37ee5b8a5a8b9cd6102b2c

addons:
  - name: logsearch-dns
    exclude:
      deployments: ["logservice", "logsearch"]
    jobs:
      - name: logsearch-dns
        release: logservice
