releases:
  - name: logservice
    version: "1.7"
    url: https://github.com/orange-cloudfoundry/logservice-release/releases/download/v1.7/logservice-1.7.tgz
    sha1: a7e642124157d837e567a4087f01c698d444a356

addons:
  - name: logsearch-dns
    exclude:
      deployments: ["logservice", "logsearch"]
    jobs:
      - name: logsearch-dns
        release: logservice
