releases:
  - name: logservice
    version: "1.9"
    url: https://github.com/orange-cloudfoundry/logservice-release/releases/download/v1.9/logservice-1.9.tgz
    sha1: ca48cd485127a46b82b7c2a4719d453ffd1918e0

addons:
  - name: logsearch-dns
    exclude:
      deployments: ["logservice", "logsearch"]
    jobs:
      - name: logsearch-dns
        release: logservice
