- type: replace
  path: /instance_groups/name=adapter/jobs/name=ca_certs?/release
  value: os-conf

- type: replace
  path: /instance_groups/name=adapter/jobs/name=ca_certs/properties?/cert_list/-
  value: ((service_cf_internal_ca.certificate))

- type: replace
  path: /releases/name=os-conf?
  value:
    name: os-conf
    version: latest
